[run]
init_cmds = [
  ["go", "build", "-race","-o", "./build/influxdb-srelay", "."],
	["./build/influxdb-srelay", "-config", "./examples/influxdb-srelay.conf", "-logdir","./logs"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR",
]
watch_exts = [".go", ".conf"]
build_delay = 1500
cmds = [
  ["go", "build", "-race","-o", "./bin/syncflux", "./pkg/"],
	["./build/influxdb-srelay","-config","./examples/influxdb-srelay.conf","-logdir","./logs"]
]
