[run]
init_cmds = [
  ["go", "build", "-race","-o", "./build/influxdb-srelay", "./pkg/"],
	["./build/influxdb-srelay", "-config", "./test/relay.devel.conf", "-logs","./logs"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR",
]
watch_exts = [".go", ".conf"]
build_delay = 1500
cmds = [
  ["go", "build", "-race","-o", "./build/influxdb-srelay", "./pkg/"],
	["./build/influxdb-srelay","-config","./test/relay.devel.conf","-logs","./logs"]
]
